#This image is used for building the app
#Build: docker build -t webapitemplate-build -f Dockerfile.build .
FROM wafflecakes/msbuild:14.0
SHELL ["powershell"]

#Copy the source
COPY . 'C:\\build\\'
WORKDIR 'C:\\build\\'

#Restore NuGet packages
RUN ["nuget.exe", "restore"]

#Build solution
RUN msbuild WebApi2Template.sln

CMD ["powershell"]
